version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - chory-amam
  ignore:
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.27"
